### ISSUE TITLE
improve defaults?

### ISSUE THREAD

**Issue by wenzowski** [KnowledgeGarden/BacksideServletKS#3]
Would be nice if `UserDatabasePath` were repo-relative instead of a full root path including drive: `./data/backside` instead of `c:/data/backside/` and we let the user `mklink` or `ln` the folder somewhere else if that's what they want.

**Comment by wenzowski** [comment]
Would a relative path break the H2DatabaseDriver on Windows? A relative path works beautifully on Ubuntu and OSX.

**Comment by KnowledgeGarden** [comment]
Would not matter, really. In BacksideServletKS, there/s already an
<install>/data directory. Not at all hard to drop userdb there.

**Comment by wenzowski** [comment]
Cool. That simplifies deployment too: putting everything in ./data means only one persistent mount point
